const ADD_TO_CART = "ADD_TO_CART";
const DELETE_FROM_CART = "DELETE_FROM_CART";
const ADD_ONE = "ADD_ONE";
const DELETE_ONE = "DELETE_ONE";

export { ADD_TO_CART, DELETE_FROM_CART, ADD_ONE, DELETE_ONE };
